### ISSUE TITLE
having multiple Ego vehicles inside a single Simulation

### ISSUE THREAD

**Issue by Jamare-UU** [PJLab-ADG/LimSim#14]
Hi, I was wondering if it is possible to have multiple Ego vehicles to switch between/ run multiple Clients inside a single Simulation. I Co-sim with SUMO and CARLA and was hoping to have multiple vehicles with different decision-making and spectate them either simultaneous or switch between them. If this is not natively supported by LimSim do you have an idea how I can achieve that?

**Comment by zijinoier** [comment]
I am sorry but I think multi-ego vehicles are not currently supported by LimSim, CARLA itself support multi-client mode though. You can check it out on https://carla.readthedocs.io/en/latest/adv_traffic_manager/#multi-client-simulations
