### ISSUE TITLE
Some question about frenet optimal plan

### ISSUE THREAD

**Issue by AntaiXie** [PJLab-ADG/LimSim#15]
Hello, if the USE.DECISION-MAKER in the config file is False, the generated trajectory will not change lanes? Because I found that if the vehicle behavior is not changed, it is always KL, so the trajectory for keeping the lane will be generated by "def lanekeeping_trajectory_generator"

**Comment by wenjie-2000** [comment]
The parameter `USE_DECISION_MAKER` specifies whether or not to use the decision module in the simulation. When `USE_DECISION_MAKER` is False, vehicles can still change lanes. 

Vehicle's behavior is maintained through a state machine. In line 136 of the file `trafficManager/traffic_manager.py`, the vehicle state machine can be updated by the function `vehicle.update_behaviour(roadgraph, KEY_INPUT)`, which ensures that the vehicle follows the given route.

If you need to get more information about the decision module, you can check out `Decision-making` in Part B of Section IV in the [paper](https://arxiv.org/abs/2307.06648).
