### ISSUE TITLE
关于能否鼠标点击车道输出车道坐标的问题

### ISSUE THREAD

**Issue by caoDavie** [PJLab-ADG/LimSim#17]
![image](https://github.com/PJLab-ADG/LimSim/assets/68193785/8560ee92-36c2-4616-92c2-67d6f7201544)
![image](https://github.com/PJLab-ADG/LimSim/assets/68193785/6a43e785-a016-439e-abf9-53ccdc4b8086)
大佬您好，现在我想添加一个自定义功能：在点击车道时得到该车道的edge_id，就像sumo里面那样。这样方便我设置起点和终点坐标来规划路径。拜读您们的代码后还是对车道展示的逻辑不太清楚，能否请大佬给出一点思路吗？

**Comment by Fdarco** [comment]
LimSim 使用 dearpygui 作为前端，点击功能可能需要调研 dearpygui 的文档才能修改。不过更简单的办法是直接在 sumo-gui 中进行这个工作，两边路网是一致的。
