### ISSUE TITLE
Some problems about the start

### ISSUE THREAD

**Issue by hairuoliu1** [PJLab-ADG/LimSim#18]
![Screenshot from 2024-03-15 16-41-39](https://github.com/PJLab-ADG/LimSim/assets/79040463/70788572-5d83-4093-9bf2-559b6c8e2cd9)
What are the possible problems?

**Comment by Fdarco** [comment]
Hello, based on the images you provided, LimSim++ seems to start up properly. If the issue you are referring to is the lack of front view images, you need to check if Co-Simulation for CARLA is working properly.

**Comment by hairuoliu1** [comment]
Thanks

**Comment by weizhou1991** [comment]
Hi, did you solve this problem? I got this problem, too. But I have no idea how to solve it
