### ISSUE TITLE
Can this simulator run in MacOS?

### ISSUE THREAD

**Issue by Bmithbs** [PJLab-ADG/LimSim#19]
Can this simulator run in MacOS?

**Comment by Fdarco** [comment]
Sorry, we haven't tested it on macOS. We prefer to run the code on a Linux system, of which Ubuntu 20.04 is the system we use for development.

**Comment by Mahonehan** [comment]
What is this minimum configuration?

**Comment by Fdarco** [comment]
We don't actually test for minimum recommended performance, so we can't answer your question very well. However, if you are going to run CARLA Co-Simulation, your computer should meet at least the minimum performance requirements of CARLA. The following are references for CARLA configuration:
- https://carla.readthedocs.io/en/latest/build_linux/
- https://carla.readthedocs.io/en/latest/build_windows/
