### ISSUE TITLE
how to use co-simulation with carla?

### ISSUE THREAD

**Issue by TeleYuhao** [PJLab-ADG/LimSim#2]
Limsim is a creative software for traffic simulation.But I can't find the content for co-simulation with carla and create  my own scenario.
Also ,the sumo network file and the route file seems don't seem to match well.
Looking forward to further improvement of the software and its user doc.

**Comment by zijinoier** [comment]
Hi, Thanks for your interest of LimSim.
We have just added the docs about how to perform cosimulation with CARLA,  See the link below: https://pjlab-adg.github.io/LimSim/GettingStarted/carla_cosim/
Besides,  could you please provide more details about the problem about sumo network and route files?

**Comment by TeleYuhao** [comment]
Thanks for your replay, I have seen the new doc. The problem I met may be beacuse the route file don't match the network file, I had solved it through the tool whose name is randomTrip.py.
what's more, I found that there is still room for further improvement in the user doc, such as the customization part. 
Looking forawrd to seeing your more comprehensive user doc  and better Limsim

**Comment by zijinoier** [comment]
Thank you for your understanding and feedback!
As a small team, we currently lack the resources to create an all-inclusive user documentation. However, having an open-source codebase allows users to explore advanced features by directly inspecting the code.

If community members encounter aspects that could benefit from additional documentation, we welcome pull requests. We'd be happy to merge relevant contributions into our documentation website. 
Your effort is valuable in making LimSim better😊
