### ISSUE TITLE
'sqlite3.OperationalError: unable to open database file' error.

### ISSUE THREAD

**Issue by dogiesalibi** [PJLab-ADG/LimSim#22]
runing python ExampleLLMAgentCloseLoop.py gives 'sqlite3.OperationalError: unable to open database file' error.
![image](https://github.com/PJLab-ADG/LimSim/assets/107478711/788e04e0-c006-4372-ba7d-c44d1632213b)

**Comment by baibingren** [comment]
me too
![image](https://github.com/PJLab-ADG/LimSim/assets/58762985/d6c857d3-f9df-4d87-832f-8807399fc8e4)

**Comment by baibingren** [comment]
![image](https://github.com/PJLab-ADG/LimSim/assets/58762985/75fd9350-829d-479f-9b24-c57fe93f674e)
I mkdir results folder by myself, then it is work

**Comment by dogiesalibi** [comment]
> ![image](https://private-user-images.githubusercontent.com/58762985/315058794-75fd9350-829d-479f-9b24-c57fe93f674e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDEyNTMsIm5iZiI6MTcxMTAwMDk1MywicGF0aCI6Ii81ODc2Mjk4NS8zMTUwNTg3OTQtNzVmZDkzNTAtODI5ZC00NzlmLTliMjQtYzU3ZmU5M2Y2NzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA2MDIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZDAzNmI0NTEzNGRhMDVjMDJlMTRhYjMwNTYzMmQ5NDRhYzAxYTM2ODBhNjliZTUwZDM0N2I3YjQzZTQ3OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SkMKAu-bv4bzfGvnyEmEQ7rRHgKvUNCBNwWRs_zOMRY) I mkdir results folder by myself, then it is work

This works, great! thanks:)
