### ISSUE TITLE
can not connect to 127.0.0.1:2000

### ISSUE THREAD

**Issue by weizhou1991** [PJLab-ADG/LimSim#24]
Hi there, 

I meet a strange problem that, I used a docker pulled from carla as the server, and I tried the SUMO demo  "python3 run_synchronization.py examples/Town04.sumocfg  --sumo-gui"
which works fine, however, I tried your "ExampleModel.py" , RuntimeError: time-out of 2000ms while waiting for the simulator, make sure the simulator is ready and connected to 127.0.0.1:2000, I read the code, I found the host and port are the same, I am so confused, did I make something wrong ? I really appreciate that you can help me out here. Thank you so much 

Best,

**Comment by Fdarco** [comment]
Thanks for using LimSim++, I see you used the Town04 road network, did you process the Town04 road network yourself? Since we haven't seen the specifics of the road network you're using, there's no way to know what's wrong with it.

**Comment by weizhou1991** [comment]
> Thanks for using LimSim++, I see you used the Town04 road network, did you process the Town04 road network yourself? Since we haven't seen the specifics of the road network you're using, there's no way to know what's wrong with it.

Thank you so much for replying, What do you mean "process the Town04 road network" I did that for test the connection of co-sim for SUMO to see if SUMO works. Because I tried your LLM test code and I have nothing show up in my window, which I found the answer for one case, you suggeset to check does the co-simulation works or not.  
After I check it, I found it does works, however, I still can not  use ur code to connect carla. I really confused about that.

**Comment by weizhou1991** [comment]
> Thanks for using LimSim++, I see you used the Town04 road network, did you process the Town04 road network yourself? Since we haven't seen the specifics of the road network you're using, there's no way to know what's wrong with it.
![image](https://github.com/PJLab-ADG/LimSim/assets/110662434/de3930f0-7ce6-44ea-91d7-9f8bd4e6becb)
I followed this to test the SUMO co-simulation

**Comment by weizhou1991** [comment]
> Thanks for using LimSim++, I see you used the Town04 road network, did you process the Town04 road network yourself? Since we haven't seen the specifics of the road network you're using, there's no way to know what's wrong with it.

Alright, I found out why, because my pc is not that good , needs more than 2000ms to load carla ... Thank you so much for your reply....

**Comment by weizhou1991** [comment]
> Thanks for using LimSim++, I see you used the Town04 road network, did you process the Town04 road network yourself? Since we haven't seen the specifics of the road network you're using, there's no way to know what's wrong with it.

![image](https://github.com/PJLab-ADG/LimSim/assets/110662434/b8d0c99f-0adb-482f-98ce-636f15e66963)
Is it right that no prompt and message come out for "ExampleModel.py" ?

**Comment by Fdarco** [comment]
> > Thanks for using LimSim++, I see you used the Town04 road network, did you process the Town04 road network yourself? Since we haven't seen the specifics of the road network you're using, there's no way to know what's wrong with it.
> 
> ![image](https://private-user-images.githubusercontent.com/110662434/315943146-b8d0c99f-0adb-482f-98ce-636f15e66963.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTcwMTMsIm5iZiI6MTcxMTA5NjcxMywicGF0aCI6Ii8xMTA2NjI0MzQvMzE1OTQzMTQ2LWI4ZDBjOTlmLTBhZGItNDgyZi05OGNlLTYzNmYxNWU2Njk2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwODM4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTExZDE4MzY2Mjk2MDQxMGNiZDE3YTI4OTBjNzg3NGNiOGU0NTFhNDQ4MzFiODcyYmM5ODczNjE1MWQ5MzExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UoZ8vvRUcDP_ZamhCig47d4M4anJS1yiiC1rvgNj8GY) Is it right that no prompt and message come out for "ExampleModel.py" ?

Yes, the prompt box won't have a message if you're not using MLLM for decision making.

**Comment by Fdarco** [comment]
> > Thanks for using LimSim++, I see you used the Town04 road network, did you process the Town04 road network yourself? Since we haven't seen the specifics of the road network you're using, there's no way to know what's wrong with it.
> > ![image](https://private-user-images.githubusercontent.com/110662434/315939300-de3930f0-7ce6-44ea-91d7-9f8bd4e6becb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTcwMTMsIm5iZiI6MTcxMTA5NjcxMywicGF0aCI6Ii8xMTA2NjI0MzQvMzE1OTM5MzAwLWRlMzkzMGYwLTdjZTYtNDRlYS05MWQ3LTlmOGJkNGU2YmVjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwODM4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTAzNjMxNTU0Y2UwNTgxMjU4M2Y2NzBhNWI0NzEwMDAwYzkyZDcyZmYxMmUzZmE0ZTYzOGM4MzA2ZmQzNWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aDfjuG6n9Iqternc0SQ_9J7mhxDHTXGdh68lPbXU670)
> > I followed this to test the SUMO co-simulation

May I ask where you saw this documentation, we have not tested it on Town04 and there should be an error in the documentation. Please provide a link to this documentation and we will fix it.

**Comment by weizhou1991** [comment]
> > > Thanks for using LimSim++, I see you used the Town04 road network, did you process the Town04 road network yourself? Since we haven't seen the specifics of the road network you're using, there's no way to know what's wrong with it.
> > > ![image](https://private-user-images.githubusercontent.com/110662434/315939300-de3930f0-7ce6-44ea-91d7-9f8bd4e6becb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTcwMTMsIm5iZiI6MTcxMTA5NjcxMywicGF0aCI6Ii8xMTA2NjI0MzQvMzE1OTM5MzAwLWRlMzkzMGYwLTdjZTYtNDRlYS05MWQ3LTlmOGJkNGU2YmVjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwODM4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTAzNjMxNTU0Y2UwNTgxMjU4M2Y2NzBhNWI0NzEwMDAwYzkyZDcyZmYxMmUzZmE0ZTYzOGM4MzA2ZmQzNWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aDfjuG6n9Iqternc0SQ_9J7mhxDHTXGdh68lPbXU670)
> > > I followed this to test the SUMO co-simulation
> 
> May I ask where you saw this documentation, we have not tested it on Town04 and there should be an error in the documentation. Please provide a link to this documentation and we will fix it.

https://carla.readthedocs.io/en/latest/adv_sumo/ here it is

**Comment by weizhou1991** [comment]
> > > Thanks for using LimSim++, I see you used the Town04 road network, did you process the Town04 road network yourself? Since we haven't seen the specifics of the road network you're using, there's no way to know what's wrong with it.
> > > ![image](https://private-user-images.githubusercontent.com/110662434/315939300-de3930f0-7ce6-44ea-91d7-9f8bd4e6becb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTcwMTMsIm5iZiI6MTcxMTA5NjcxMywicGF0aCI6Ii8xMTA2NjI0MzQvMzE1OTM5MzAwLWRlMzkzMGYwLTdjZTYtNDRlYS05MWQ3LTlmOGJkNGU2YmVjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwODM4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTAzNjMxNTU0Y2UwNTgxMjU4M2Y2NzBhNWI0NzEwMDAwYzkyZDcyZmYxMmUzZmE0ZTYzOGM4MzA2ZmQzNWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aDfjuG6n9Iqternc0SQ_9J7mhxDHTXGdh68lPbXU670)
> > > I followed this to test the SUMO co-simulation
> 
> May I ask where you saw this documentation, we have not tested it on Town04 and there should be an error in the documentation. Please provide a link to this documentation and we will fix it.
Hi, 

I got "ExampleModel.py" run great, however, when I tried " ExampleLLMAgentCloseLoop.py" I got this: 
![image](https://github.com/PJLab-ADG/LimSim/assets/110662434/a1a6bfad-eea9-493b-bd0e-76b39e92cfb5)
The output of terminl shows like this: 
![image](https://github.com/PJLab-ADG/LimSim/assets/110662434/3434cc55-49bd-4a55-a559-1e6c4b447a11)
What kind of images can I have if it runs well? And could you give me a hit where I might be wrong for running your example ? 

Best,

**Comment by Fdarco** [comment]
It is true that `ExampleLLMAgentCloseLoop.py` will not provide a front view image. If you want to see the front-view image, you should run `ExampleVLMAgentCloseLoop.py`

**Comment by weizhou1991** [comment]
> It is true that `ExampleLLMAgentCloseLoop.py` will not provide a front view image. If you want to see the front-view image, you should run `ExampleVLMAgentCloseLoop.py`

sounds like I should get a GPT4-V key to run it. DO I have any way to change the VLM to Qwen-VL or LLaVA, etc?

**Comment by Fdarco** [comment]
You can refer to our code to build a driver agent based on Qwen-VL, we don't provide this piece of code at the moment. Feel free to give me a PR if you have done this work.
