### ISSUE TITLE
ModuleNotFoundError: No module named 'carla'

### ISSUE THREAD

**Issue by wang123yuan** [PJLab-ADG/LimSim#27]
`Traceback (most recent call last): File "ExampleVLMAgentCloseLoop.py", line 225, in <module> model.start() File "/home/v2t/LimSim/simModel/Model.py", line 177, in start from sumo_integration.run_synchronization import getSynchronization File "/home/v2t/LimSim/sumo_integration/run_synchronization.py", line 39, in <module> import carla # pylint: disable=import-error ModuleNotFoundError: No module named 'carla' `

When I run ExampleVLMAgentCloseLoop.py,What can I do if I get the above error?

**Comment by Fdarco** [comment]
You should install `carla` package before you run this code.

**Comment by wang123yuan** [comment]
> You should install `carla` package before you run this code.您应该在运行此代码之前安装 `carla` 包。
The screen is displayed normally, but it is very stuck. ...
![屏幕截图 2024-04-08 224618](https://github.com/PJLab-ADG/LimSim/assets/134376989/b0e07587-0827-4494-80a4-d631105fc8d1)

**Comment by Fdarco** [comment]
LLM inference is slow and the program waits for LLM making an answer before running, so lagging is normal.

**Comment by wang123yuan** [comment]
> LLM inference is slow and the program waits for LLM making an answer before running, so lagging is normal.

Ok, thanks for your reply. Does your demo video look smooth because it speeds up LLM inference?

**Comment by Fdarco** [comment]
Yes, it is a replay video, you can run the `ExampleReplay.py` to view the result.
