### ISSUE TITLE
EGO car and the surrounding cars

### ISSUE THREAD

**Issue by AntaiXie** [PJLab-ADG/LimSim#30]
Hello, I would like to know if both the EGO car and surrounding cars are controlled by the LLM model? Also, can we implement our own model to control the EGO car and the LLM model to control the surrounding traffic flow, just like Limsim？

**Comment by Fdarco** [comment]
Hello, it seems that you are using LimSim++. In our sample code, `roadgraph, vehicles = model.exportSce()` exports the road network environment around the current frame EGO and the information of surrounding vehicles. You can print these data to view their content. `roadgraph` and `vehicles` can be input into your own control model to obtain the trajectory of the vehicle, or meta-action. Then, you can use `model.setTrajectories(trajectories)` to control the movement of the vehicle.
LimSim++ supports LLM driving, but it also supports rule-based or learning-based methods for driving. You can freely choose which method to use and which vehicles to control.
