### ISSUE TITLE
The mismatch offset of Town01 in Co-simulation with carla

### ISSUE THREAD

**Issue by Sephiroth1118** [PJLab-ADG/LimSim#32]
Hello! I'm just using Limsim. The default map for carla co-simulation is Town05. When I tried to change to Town01, I found a mismatch position offset between Carla and sumo. I tried to change the netOffset in net.xml file but no effects. May I ask what the problem might be?
![Screenshot from 2024-08-20 16-22-25](https://github.com/user-attachments/assets/7c91af64-3ac3-4a36-9802-2a3ece4b8044)

**Comment by Fdarco** [comment]
Hello, thank you for using LimSim. From the pictures you provided, it seems that the ego car in CARLA and the ego car in LimSim are not aligned. Did you set the ego car id in CARLA? In addition, in LimSim, co-simulation with CARLA requires instrumentation settings, so we recommend using [LimSim++](https://github.com/PJLab-ADG/LimSim/tree/LimSim_plus) if you need to obtain data from CARLA.

**Comment by Sephiroth1118** [comment]
Hi! Thank you so much for your reply! I finally found out what is wrong. The rou.xml in sumo is mismatched.
