### ISSUE TITLE
在 CARLA 中更改鸟瞰视图报错

### ISSUE THREAD

**Issue by hao-xiaoxing** [PJLab-ADG/LimSim#36]
执行如下指令无反应

(lim) hxx@hxx-System-Product-Name:/workspace/SIM/test/LimSim$ python ./ModelExample.py
Model initialized at 18:17:59.793.
Network building finished at 18:18:02.059.
 Retrying in 1 seconds
Network information commited at 18:18:02.113.

**Comment by Fdarco** [comment]
I'm sorry to hear you're having this issue. However, I didn't understand what you did. Could you show the specific code you modified?

**Comment by hao-xiaoxing** [comment]
> I'm sorry to hear you're having this issue. However, I didn't understand what you did. Could you show the specific code you modified?

我按照这个流程进行操作。run_model(net_file, rou_file, ego_veh_id="4", carla_cosim=True)，当carla_cosim为False可执行，为True则任何反应

![limsim](https://github.com/user-attachments/assets/a1d91e7f-ae25-426a-8c99-e429a6f8dee9)

**Comment by Fdarco** [comment]
Do you download and replace the `run_synchronization.py` file?

**Comment by hao-xiaoxing** [comment]
> > I'm sorry to hear you're having this issue. However, I didn't understand what you did. Could you show the specific code you modified?
> 
> 我按照这个流程进行操作。run_model(net_file, rou_file, ego_veh_id="4", carla_cosim=True)，当carla_cosim为False可执行，为True则任何反应
> 
> ![limsim](https://private-user-images.githubusercontent.com/63962391/378245047-a1d91e7f-ae25-426a-8c99-e429a6f8dee9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NzUyMzMsIm5iZiI6MTcyOTQ3NDkzMywicGF0aCI6Ii82Mzk2MjM5MS8zNzgyNDUwNDctYTFkOTFlN2YtYWUyNS00MjZhLThjOTktZTQyOWE2ZjhkZWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDAxNDIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYjkwMDk5NGI3Nzg5NDRhNzJkZTdkZGVhOGQ0MmE1YzFjMTc3YmI5NmI2MmRlNGMxMTRkNTUwYjAxYWFlOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wH11Am1S8nfxBG8-4mSQZRzjcxXIdT7jkeRG6_yANew)

carla第一个终端执行 ./CarlaUE4.sh -world-port=2000 -resx=400 -resy=300 -quality-level=Epic；第二个终端执行 python3 config.py --map Town05；然后按照替换run_synchronization.py，并确保ego_id=‘4’，最后执行ModelExample.py

**Comment by hao-xiaoxing** [comment]
> Do you download and replace the `run_synchronization.py` file?

yes

**Comment by hao-xiaoxing** [comment]
> Do you download and replace the `run_synchronization.py` file?

我重新下载安装了limsim代码，以及其对应的虚拟环境；并重新下载替换了run_synchronization.py，确保ego_id匹配（都为4），但结果仍然与之前一致

**Comment by Fdarco** [comment]
Could you show the output messages of the three terminals?

**Comment by hao-xiaoxing** [comment]
![01](https://github.com/user-attachments/assets/0aff2bf9-c5a9-42ce-b6fe-6d58b45b4b73)
![02](https://github.com/user-attachments/assets/e91dfcea-4ad5-4d77-b322-f7e5da558a0a)
![03](https://github.com/user-attachments/assets/26bd14b8-44eb-4e55-a9c4-27b546648a9c)
结果如上

**Comment by Fdarco** [comment]
It seems that you weren't successful in switching maps on the second terminal. This might be due to a mismatch between your simulator version and your API version.

**Comment by hao-xiaoxing** [comment]
当我设置为carla_cosim为False，其可以出现展示的结果，但终端仍然是下图这样，
![04](https://github.com/user-attachments/assets/dc1f3140-c656-4830-88ef-f425d8fcbbaf)
如果simulator与API 版本不一致，如何解决？

**Comment by hao-xiaoxing** [comment]
> It seems that you weren't successful in switching maps on the second terminal. This might be due to a mismatch between your simulator version and your API version.

我执行第二个终端时，map切换成功了

**Comment by Fdarco** [comment]
When you set carla_cosim=False, there is actually no connection with CARLA, so it can run correctly. For version selection between the simulator and API, please refer to the official CARLA documentation.

**Comment by Fdarco** [comment]
> 当我设置为carla_cosim为False，其可以出现展示的结果，但终端仍然是下图这样， ![04](https://private-user-images.githubusercontent.com/63962391/378255116-dc1f3140-c656-4830-88ef-f425d8fcbbaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NzkwNTYsIm5iZiI6MTcyOTQ3ODc1NiwicGF0aCI6Ii82Mzk2MjM5MS8zNzgyNTUxMTYtZGMxZjMxNDAtYzY1Ni00ODMwLTg4ZWYtZjQyNWQ4ZmNiYmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDAyNDU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNWJlOTIwMzMyMzhlMDBmMTA1ZThmNzRkZmEzMjY3ZDI4NTFhMjg2Y2YxZWRlOWM2YjlmN2M0MjNhNjk2YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2yeYUUzVJ0mhQhgvfXyo_ne_m3Ph-_QQpJlDaXzGUVM) 如果simulator与API 版本不一致，如何解决？

Actually, this is indeed the correct output.

**Comment by hao-xiaoxing** [comment]
这个是我的版本：
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.15 
WARNING: Simulator API version  = 0.9.15-228-geeb507e58 

这个是carla官网的问题和答案：
![05](https://github.com/user-attachments/assets/721fe9a0-1d11-4329-904e-bed643f51aa4)
![06](https://github.com/user-attachments/assets/30f485f8-fd40-4104-aec0-ca06b22dce17)

carla官网是将client版本提升至0.9.15，而0.9.15-228-geeb507e58 是不可更改的。如果方便，您可以提供一下您的Client API version和Simulator API version 吗？

**Comment by Fdarco** [comment]
In the `your_carla_path/PythonAPI/carla/dist` folder, there are compiled files for the CARLA API. You can try installing them.

**Comment by hao-xiaoxing** [comment]
> In the `your_carla_path/PythonAPI/carla/dist` folder, there are compiled files for the CARLA API. You can try installing them

我尝试了，没有任何改变，我觉着这是实现这个功能。Client API version = 0.9.15，而我本身就是这样的

**Comment by Fdarco** [comment]
Based on the information you provided, we cannot pinpoint the specific issue. Perhaps you could try [LimSim++](https://github.com/PJLab-ADG/LimSim/tree/LimSim_plus), as it is easier to implement co-simulation.

**Comment by hao-xiaoxing** [comment]
> Based on the information you provided, we cannot pinpoint the specific issue. Perhaps you could try [LimSim++](https://github.com/PJLab-ADG/LimSim/tree/LimSim_plus), as it is easier to implement co-simulation.

ok,thank you!

**Comment by hao-xiaoxing** [comment]
> Based on the information you provided, we cannot pinpoint the specific issue. Perhaps you could try [LimSim++](https://github.com/PJLab-ADG/LimSim/tree/LimSim_plus), as it is easier to implement co-simulation.

抱歉，我目前遇到两种carla版本，一种是网页版，带有./CarlaUE4.sh文件；另一种是git clone https://github.com/carla-simulator/carla，不带./CarlaUE4.sh；我按照操作感觉应该是第一种，但是我在carla官网报错的解决方案都是第二种的解决方案
![07](https://github.com/user-attachments/assets/e0a2586e-575a-4650-ac10-11ba90cba9a9)
如果方便，麻烦给个联系方式，我好跟您请教一下，确实刚接触这个方向！
