### ISSUE TITLE
Does limsim will or can support different kind of Kinematics model such  as tractor-trailer vehicle?

### ISSUE THREAD

**Issue by TeleYuhao** [PJLab-ADG/LimSim#4]
Does limsim will or can support different kind of Kinematics model such  as tractor-trailer vehicle?
If it could be achieved through customization, how can I modify the code?

**Comment by zijinoier** [comment]
Hi there, that's an interesting question!

Currently, the planner used in LimSim is based on the [Optimal Trajectory Generation in a Frenet Frame](https://www.researchgate.net/profile/Moritz_Werling/publication/224156269_Optimal_Trajectory_Generation_for_Dynamic_Street_Scenarios_in_a_Frenet_Frame/links/54f749df0cf210398e9277af.pdf) method. For implementation details, you can refer to `trafficManager/planner/frenet_optimal_planner/frenet_optimal_planner.py`.

It's important to note that this method mainly considers Ackermann Kinematic model cars. The `check_path` function in the above file restricts the output trajectories in terms of maximum acceleration, maximum speed, and turning radius.

If you need a planner suitable for tractor-trailer vehicles or require more precise planning, we suggest implementing your own planner class based on the `AbstractEgoPlanner` class found in `trafficManager/planner/abstract_planner.py`. 

We looking forward your implementation and will be glad to have your contribution in LimSim!

**Comment by TeleYuhao** [comment]
Thanks for your reply.  This is a interesting part for simulation software. If it is possible , I will do some efforts to achieve this and More communication with you.

**Comment by zijinoier** [comment]
Great, And if you're interested, please join our user community on WeChat:

<img src="https://github.com/PJLab-ADG/LimSim/assets/18390668/bdad44cc-0555-41c4-a780-51634f3ad849" width="500">
