### ISSUE TITLE
Can not open Traffic Simulator

### ISSUE THREAD

**Issue by ldt17** [PJLab-ADG/LimSim#7]
We try your Quick Start and build the environment with python=3.9.18 and sumolib = 1.16 . But the Traffic Simulator shows nothing with no error.
![1695026347840](https://github.com/PJLab-ADG/LimSim/assets/58940649/05d4b37a-99ac-4185-92db-dd1a10391d60)

**Comment by Fdarco** [comment]
Hello, I noticed that you have set the `carla_cosim` parameter to `True`. Are you planning to do a co-simulation? If not, please try setting this parameter to `False` and run it again.

**Comment by ldt17** [comment]
@Fdarco Thanks for your recommendation. In fact, I have tried both “True” and “False” and obtained the same results which shows nothing with no error.

**Comment by Fdarco** [comment]
Did you modify any other code? Or did this problem occur directly when running the code?

**Comment by ldt17** [comment]
> Did you modify any other code? Or did this problem occur directly when running the code?

@Fdarco No, I'm just trying your Quick Start but failed. We haven't even reached the stage of co-simulation yet.
![image](https://github.com/PJLab-ADG/LimSim/assets/58940649/57045c05-945a-4478-850b-a7e18a88b1ec)

When we run this code, it becomes unresponsive. The window “TrafficSimulator” will open, but there is nothing on the screen except white.
![1695031867542](https://github.com/PJLab-ADG/LimSim/assets/58940649/1e4f267e-6e9e-4e32-812f-6b21af5ec184)

**Comment by Fdarco** [comment]
I’m sorry for the inconvenience. However, I created a new environment in conda with python=3.9.18 and reinstalled the dependencies, and I was not able to reproduce your issue. I noticed that there was a problem with con.getVsersion() in your original Tracback. May I ask what version of SUMO you have installed? 
Here are the results when I run it in the new environment:
![issue7](https://github.com/PJLab-ADG/LimSim/assets/26219929/8ebc2cac-eb2f-4c43-81a0-15bd6354c18a)
![image](https://github.com/PJLab-ADG/LimSim/assets/26219929/595e24b6-3598-4e50-904c-4dfd3dcdaf33)

**Comment by ldt17** [comment]
@Fdarco We completely followed the process in Quick Start, using pip install -r requirements.txt. The following is the installation environment details. Thanks.
![image](https://github.com/PJLab-ADG/LimSim/assets/58940649/ec9e645f-4f66-49bb-ab43-03e72dacdee4)

**Comment by ldt17** [comment]
@Fdarco The version of SUMO is 1.18.0. 
![image](https://github.com/PJLab-ADG/LimSim/assets/58940649/e1a74e8a-b5d6-440d-9f7c-0154938b7db9)
And I also found that if the “sumogui” in the modelexample.py file is set to 1, the “sumogui” interface can be opened, but the traffic simulator interface still cannot be opened.
![1695125217777](https://github.com/PJLab-ADG/LimSim/assets/58940649/3b0eaceb-c35f-4d77-9f78-8717d656370b)

**Comment by Fdarco** [comment]
Although I cannot guarantee its effectiveness, I suspect it may be due to the backward compatibility of the versions of sumolib and traci. In fact, we have only tested SUMO before version 1.16. If possible, please try installing a lower version of SUMO or upgrading sumolib and traci to the latest version.

**Comment by ldt17** [comment]
@Fdarco  We have tried the same process on other devices and found that it runs normally. The sumo versions are 1.18 and 1.17, respectively. However, the above errors still occur on previous devices. Can we assume that the absence of the traffic simulator is not related to the sumo version

**Comment by Fdarco** [comment]
Sorry, we did not encounter similar problems during testing. If you don’t mind, can you add our WeChat account to facilitate communication? This is my WeChat ID: f17756897230

**Comment by CRHPlusAI** [comment]
I encounter the same issue. I think if you install sumo 1.16, it would resolve
either do this through `pip install eclipse-sumo==1.16.0`, or add `eclipse-sumo==1.16.0` to the requirement.txt can resolve this issue.
