### ISSUE TITLE
Replace the trajectory planning algorithm

### ISSUE THREAD

**Issue by 12num** [PJLab-ADG/LimSim#8]
How to combine the existing trajectory planning model with limsim, and can the frenet_optimal_planner.py algorithm be replaced?

**Comment by zijinoier** [comment]
Hello,
To integrate the existing planning algorithm into LimSim:
1. Extend the `abstract_planner.py` located in `trafficManager/planner/`. Create a new planner class by inheriting from this abstract planner.
2. In `trafficManager/traffic_manager.py`, initialize the `EgoPlanner` with your custom planner class.

We welcome contributions and integrations!
